// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: Response.capnp

package org.ericsson2017.protocol.semifinal;

public final class ResponseClass {
  public static class Cell {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)2,(short)0);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Cell.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final int getOwner() {
        return _getIntField(0);
      }
      public final void setOwner(int value) {
        _setIntField(0, value);
      }

      public final Attack.Builder getAttack() {
        return new Cell.Attack.Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final Attack.Builder initAttack() {
        _setBooleanField(32,false);
        _setShortField(3,(short)0);
        _setIntField(2,0);
  return new Cell.Attack.Builder(segment, data, pointers, dataSize, pointerCount);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final int getOwner() {
        return _getIntField(0);
      }

      public Attack.Reader getAttack() {
        return new Cell.Attack.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

    }

    public static class Attack {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)2,(short)0);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Cell.Attack.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public Which which() {
          switch(_getShortField(3)) {
            case 0 : return Which.CAN;
            case 1 : return Which.UNIT;
            default: return Which._NOT_IN_SCHEMA;
          }
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final boolean isCan() {
          return which() == Cell.Attack.Which.CAN;
        }
        public final boolean getCan() {
          assert which() == Cell.Attack.Which.CAN:
                      "Must check which() before get()ing a union member.";
          return _getBooleanField(32, true);
        }
        public final void setCan(boolean value) {
          _setShortField(3, (short)Cell.Attack.Which.CAN.ordinal());
          _setBooleanField(32, value, true);
        }

        public final boolean isUnit() {
          return which() == Cell.Attack.Which.UNIT;
        }
        public final int getUnit() {
          assert which() == Cell.Attack.Which.UNIT:
                      "Must check which() before get()ing a union member.";
          return _getIntField(2);
        }
        public final void setUnit(int value) {
          _setShortField(3, (short)Cell.Attack.Which.UNIT.ordinal());
          _setIntField(2, value);
        }

      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public Which which() {
          switch(_getShortField(3)) {
            case 0 : return Which.CAN;
            case 1 : return Which.UNIT;
            default: return Which._NOT_IN_SCHEMA;
          }
        }
        public final boolean isCan() {
          return which() == Cell.Attack.Which.CAN;
        }
        public final boolean getCan() {
          assert which() == Cell.Attack.Which.CAN:
                      "Must check which() before get()ing a union member.";
          return _getBooleanField(32, true);
        }

        public final boolean isUnit() {
          return which() == Cell.Attack.Which.UNIT;
        }
        public final int getUnit() {
          assert which() == Cell.Attack.Which.UNIT:
                      "Must check which() before get()ing a union member.";
          return _getIntField(2);
        }

      }

      public enum Which {
        CAN,
        UNIT,
        _NOT_IN_SCHEMA,
      }
    }


  }


  public static class Enemy {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Enemy.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final org.ericsson2017.protocol.semifinal.CommonClass.Position.Builder getPosition() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory, 0, null, 0);
      }
      public final void setPosition(org.ericsson2017.protocol.semifinal.CommonClass.Position.Reader value) {
        _setPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory,0, value);
      }
      public final org.ericsson2017.protocol.semifinal.CommonClass.Position.Builder initPosition() {
        return _initPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory,0, 0);
      }
      public final Direction.Builder getDirection() {
        return new Enemy.Direction.Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final Direction.Builder initDirection() {
        _setShortField(0,(short)0);
        _setShortField(1,(short)0);
  return new Enemy.Direction.Builder(segment, data, pointers, dataSize, pointerCount);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasPosition() {
        return !_pointerFieldIsNull(0);
      }
      public org.ericsson2017.protocol.semifinal.CommonClass.Position.Reader getPosition() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory,0,null, 0);
      }

      public Direction.Reader getDirection() {
        return new Enemy.Direction.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

    }

    public static class Direction {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Enemy.Direction.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final org.ericsson2017.protocol.semifinal.CommonClass.Direction getVertical() {
          switch(_getShortField(0)) {
            case 0 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.UP;
            case 1 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.LEFT;
            case 2 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.DOWN;
            case 3 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.RIGHT;
            default: return org.ericsson2017.protocol.semifinal.CommonClass.Direction._NOT_IN_SCHEMA;
          }
        }
        public final void setVertical(org.ericsson2017.protocol.semifinal.CommonClass.Direction value) {
          _setShortField(0, (short)value.ordinal());
        }

        public final org.ericsson2017.protocol.semifinal.CommonClass.Direction getHorizontal() {
          switch(_getShortField(1)) {
            case 0 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.UP;
            case 1 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.LEFT;
            case 2 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.DOWN;
            case 3 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.RIGHT;
            default: return org.ericsson2017.protocol.semifinal.CommonClass.Direction._NOT_IN_SCHEMA;
          }
        }
        public final void setHorizontal(org.ericsson2017.protocol.semifinal.CommonClass.Direction value) {
          _setShortField(1, (short)value.ordinal());
        }

      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final org.ericsson2017.protocol.semifinal.CommonClass.Direction getVertical() {
          switch(_getShortField(0)) {
            case 0 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.UP;
            case 1 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.LEFT;
            case 2 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.DOWN;
            case 3 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.RIGHT;
            default: return org.ericsson2017.protocol.semifinal.CommonClass.Direction._NOT_IN_SCHEMA;
          }
        }

        public final org.ericsson2017.protocol.semifinal.CommonClass.Direction getHorizontal() {
          switch(_getShortField(1)) {
            case 0 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.UP;
            case 1 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.LEFT;
            case 2 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.DOWN;
            case 3 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.RIGHT;
            default: return org.ericsson2017.protocol.semifinal.CommonClass.Direction._NOT_IN_SCHEMA;
          }
        }

      }

    }


  }


  public static class Unit {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)2,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Unit.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final int getOwner() {
        return _getIntField(0);
      }
      public final void setOwner(int value) {
        _setIntField(0, value);
      }

      public final org.ericsson2017.protocol.semifinal.CommonClass.Position.Builder getPosition() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory, 0, null, 0);
      }
      public final void setPosition(org.ericsson2017.protocol.semifinal.CommonClass.Position.Reader value) {
        _setPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory,0, value);
      }
      public final org.ericsson2017.protocol.semifinal.CommonClass.Position.Builder initPosition() {
        return _initPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory,0, 0);
      }
      public final org.ericsson2017.protocol.semifinal.CommonClass.Direction getDirection() {
        switch(_getShortField(2)) {
          case 0 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.UP;
          case 1 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.LEFT;
          case 2 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.DOWN;
          case 3 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.RIGHT;
          default: return org.ericsson2017.protocol.semifinal.CommonClass.Direction._NOT_IN_SCHEMA;
        }
      }
      public final void setDirection(org.ericsson2017.protocol.semifinal.CommonClass.Direction value) {
        _setShortField(2, (short)value.ordinal());
      }

      public final int getHealth() {
        return _getIntField(2, 3);
      }
      public final void setHealth(int value) {
        _setIntField(2, value, 3);
      }

      public final int getKiller() {
        return _getIntField(3, 6);
      }
      public final void setKiller(int value) {
        _setIntField(3, value, 6);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final int getOwner() {
        return _getIntField(0);
      }

      public boolean hasPosition() {
        return !_pointerFieldIsNull(0);
      }
      public org.ericsson2017.protocol.semifinal.CommonClass.Position.Reader getPosition() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.CommonClass.Position.factory,0,null, 0);
      }

      public final org.ericsson2017.protocol.semifinal.CommonClass.Direction getDirection() {
        switch(_getShortField(2)) {
          case 0 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.UP;
          case 1 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.LEFT;
          case 2 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.DOWN;
          case 3 : return org.ericsson2017.protocol.semifinal.CommonClass.Direction.RIGHT;
          default: return org.ericsson2017.protocol.semifinal.CommonClass.Direction._NOT_IN_SCHEMA;
        }
      }

      public final int getHealth() {
        return _getIntField(2, 3);
      }

      public final int getKiller() {
        return _getIntField(3, 6);
      }

    }

  }


  public static class Response {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)2,(short)4);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Response.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasStatus() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getStatus() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setStatus(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setStatus(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initStatus(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final Info.Builder getInfo() {
        return new Response.Info.Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final Info.Builder initInfo() {
        _setIntField(0,0);
        _setIntField(1,0);
        _setIntField(2,0);
  return new Response.Info.Builder(segment, data, pointers, dataSize, pointerCount);
      }

      public final boolean hasCells() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.ListList.Builder<org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Builder>> getCells() {
        return _getPointerField(new org.capnproto.ListList.Factory<org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Builder>, org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Reader>>(org.ericsson2017.protocol.semifinal.ResponseClass.Cell.listFactory), 1, null, 0);
      }
      public final void setCells(org.capnproto.ListList.Reader<org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Reader>> value) {
        _setPointerField(new org.capnproto.ListList.Factory<org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Builder>, org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Reader>>(org.ericsson2017.protocol.semifinal.ResponseClass.Cell.listFactory), 1, value);
      }
      public final org.capnproto.ListList.Builder<org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Builder>> initCells(int size) {
        return _initPointerField(new org.capnproto.ListList.Factory<org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Builder>, org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Reader>>(org.ericsson2017.protocol.semifinal.ResponseClass.Cell.listFactory), 1, size);
      }
      public final boolean hasEnemies() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.Builder> getEnemies() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.listFactory, 2, null, 0);
      }
      public final void setEnemies(org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.Reader> value) {
        _setPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.listFactory, 2, value);
      }
      public final org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.Builder> initEnemies(int size) {
        return _initPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.listFactory, 2, size);
      }
      public final boolean hasUnits() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Unit.Builder> getUnits() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Unit.listFactory, 3, null, 0);
      }
      public final void setUnits(org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Unit.Reader> value) {
        _setPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Unit.listFactory, 3, value);
      }
      public final org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Unit.Builder> initUnits(int size) {
        return _initPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Unit.listFactory, 3, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasStatus() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getStatus() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public Info.Reader getInfo() {
        return new Response.Info.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final boolean hasCells() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.ListList.Reader<org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Reader>> getCells() {
        return _getPointerField(new org.capnproto.ListList.Factory<org.capnproto.StructList.Builder<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Builder>, org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Cell.Reader>>(org.ericsson2017.protocol.semifinal.ResponseClass.Cell.listFactory), 1, null, 0);
      }

      public final boolean hasEnemies() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.Reader> getEnemies() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Enemy.listFactory, 2, null, 0);
      }

      public final boolean hasUnits() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.StructList.Reader<org.ericsson2017.protocol.semifinal.ResponseClass.Unit.Reader> getUnits() {
        return _getPointerField(org.ericsson2017.protocol.semifinal.ResponseClass.Unit.listFactory, 3, null, 0);
      }

    }

    public static class Info {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)2,(short)4);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Response.Info.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final int getOwns() {
          return _getIntField(0);
        }
        public final void setOwns(int value) {
          _setIntField(0, value);
        }

        public final int getLevel() {
          return _getIntField(1);
        }
        public final void setLevel(int value) {
          _setIntField(1, value);
        }

        public final int getTick() {
          return _getIntField(2);
        }
        public final void setTick(int value) {
          _setIntField(2, value);
        }

      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final int getOwns() {
          return _getIntField(0);
        }

        public final int getLevel() {
          return _getIntField(1);
        }

        public final int getTick() {
          return _getIntField(2);
        }

      }

    }


  }



public static final class Schemas {
public static final org.capnproto.SegmentReader b_9ec349be4999c4ca =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00ca\u00c4\u0099\u0049\u00be\u0049\u00c3\u009e" +
   "\u000f\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u00a5\u00ec\u0041\u0078\u00d6\u00e8\u0006\u00c0" +
   "\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00a2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0043" +
   "\u0065\u006c\u006c\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0024\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0030\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e2\u0061\u00a4\u00ca\u00a3\u001f\u00af\u00da" +
   "\u002d\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006f\u0077\u006e\u0065\u0072\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0074\u0074\u0061\u0063\u006b\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_daaf1fa3caa461e2 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00e2\u0061\u00a4\u00ca\u00a3\u001f\u00af\u00da" +
   "\u0014\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u00ca\u00c4\u0099\u0049\u00be\u0049\u00c3\u009e" +
   "\u0000\u0000\u0007\u0000\u0001\u0000\u0002\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00da\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0043" +
   "\u0065\u006c\u006c\u002e\u0061\u0074\u0074\u0061" +
   "\u0063\u006b\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u00ff\u00ff\u0020\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\"\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0024\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0030\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u00fe\u00ff\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002d\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0028\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0034\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0063\u0061\u006e\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u006e\u0069\u0074\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_a9b9ddaa203d4eec =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00ec\u004e\u003d\u0020\u00aa\u00dd\u00b9\u00a9" +
   "\u000f\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u00a5\u00ec\u0041\u0078\u00d6\u00e8\u0006\u00c0" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00aa\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0045" +
   "\u006e\u0065\u006d\u0079\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0028\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0034\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c5\u0003\u0089\u0089\u0029\u0059\u0046\u00e0" +
   "\u0031\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u006f\u0073\u0069\u0074\u0069\u006f\u006e" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b3\u002b\u00db\r\u003b\u0018\u00a0\u00ec" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0069\u0072\u0065\u0063\u0074\u0069\u006f" +
   "\u006e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_e0465929898903c5 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00c5\u0003\u0089\u0089\u0029\u0059\u0046\u00e0" +
   "\u0015\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u00ec\u004e\u003d\u0020\u00aa\u00dd\u00b9\u00a9" +
   "\u0001\u0000\u0007\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u0077\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0045" +
   "\u006e\u0065\u006d\u0079\u002e\u0064\u0069\u0072" +
   "\u0065\u0063\u0074\u0069\u006f\u006e\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0000\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0028\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0034\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0031\u0000\u0000\u0000\u005a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0030\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u003c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0076\u0065\u0072\u0074\u0069\u0063\u0061\u006c" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0099\r\u00b7\u00c3\u00d8\u0047\u00a6\u009a" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0068\u006f\u0072\u0069\u007a\u006f\u006e\u0074" +
   "\u0061\u006c\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0099\r\u00b7\u00c3\u00d8\u0047\u00a6\u009a" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_e3f0a29933f791f6 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00f6\u0091\u00f7\u0033\u0099\u00a2\u00f0\u00e3" +
   "\u000f\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u00a5\u00ec\u0041\u0078\u00d6\u00e8\u0006\u00c0" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00a2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u001f\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0055" +
   "\u006e\u0069\u0074\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u007d\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0078\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0084\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0081\u0000\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0080\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u008c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0089\u0000\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0088\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0094\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0003\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0091\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u008c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0098\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0095\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0090\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u009c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u006f\u0077\u006e\u0065\u0072\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u006f\u0073\u0069\u0074\u0069\u006f\u006e" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b3\u002b\u00db\r\u003b\u0018\u00a0\u00ec" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0069\u0072\u0065\u0063\u0074\u0069\u006f" +
   "\u006e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0099\r\u00b7\u00c3\u00d8\u0047\u00a6\u009a" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0068\u0065\u0061\u006c\u0074\u0068\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006b\u0069\u006c\u006c\u0065\u0072\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_b40482839d54ca4a =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u004a\u00ca\u0054\u009d\u0083\u0082\u0004\u00b4" +
   "\u000f\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u00a5\u00ec\u0041\u0078\u00d6\u00e8\u0006\u00c0" +
   "\u0004\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00c2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u001f\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0052" +
   "\u0065\u0073\u0070\u006f\u006e\u0073\u0065\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u007d\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0078\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0084\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u001b\u00d1\u0090\u0024\"\u008a\u00a3" +
   "\u0081\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0002\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0069\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0090\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0003\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u008d\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0088\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00a4\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00a1\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u009c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00b8\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0073\u0074\u0061\u0074\u0075\u0073\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0069\u006e\u0066\u006f\u0000\u0000\u0000\u0000" +
   "\u0063\u0065\u006c\u006c\u0073\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00ca\u00c4\u0099\u0049\u00be\u0049\u00c3\u009e" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u006e\u0065\u006d\u0069\u0065\u0073\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00ec\u004e\u003d\u0020\u00aa\u00dd\u00b9\u00a9" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u006e\u0069\u0074\u0073\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f6\u0091\u00f7\u0033\u0099\u00a2\u00f0\u00e3" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_a38a222490d11b10 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u0010\u001b\u00d1\u0090\u0024\"\u008a\u00a3" +
   "\u0018\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
   "\u004a\u00ca\u0054\u009d\u0083\u0082\u0004\u00b4" +
   "\u0004\u0000\u0007\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00ea\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u00af\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0052\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
   "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u0052" +
   "\u0065\u0073\u0070\u006f\u006e\u0073\u0065\u002e" +
   "\u0069\u006e\u0066\u006f\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0045\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0040\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u004c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0049\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0044\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0050\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004d\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0048\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0054\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u006f\u0077\u006e\u0073\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006c\u0065\u0076\u0065\u006c\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0069\u0063\u006b\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
}
}

